\set ON_ERROR_STOP on

SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = 'internet_shop' AND pid <> pg_backend_pid();

DROP DATABASE IF EXISTS internet_shop;
CREATE DATABASE internet_shop;

\connect internet_shop

BEGIN;

DROP TABLE IF EXISTS delivery CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS order_statuses CASCADE;
DROP TABLE IF EXISTS product_attributes CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS manufacturers CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE categories (
  category_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE manufacturers (
  manufacturer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR(150) NOT NULL,
  country         VARCHAR(100) NOT NULL
);

CREATE TABLE products (
  product_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id      INT NOT NULL,
  manufacturer_id  INT NOT NULL,
  model_name       VARCHAR(150) NOT NULL,
  description      VARCHAR(1000),
  price            NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  assembly_place   VARCHAR(100),
  stock_qty        INT NOT NULL CHECK (stock_qty >= 0),
  warranty_months  INT NOT NULL CHECK (warranty_months >= 0),
  CONSTRAINT fk_products_category
    FOREIGN KEY (category_id) REFERENCES categories(category_id),
  CONSTRAINT fk_products_manufacturer
    FOREIGN KEY (manufacturer_id) REFERENCES manufacturers(manufacturer_id)
);

CREATE TABLE product_attributes (
  attribute_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id   INT NOT NULL,
  attr_name    VARCHAR(120) NOT NULL,
  attr_value   VARCHAR(255) NOT NULL,
  CONSTRAINT fk_attr_product
    FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE
);

CREATE TABLE customers (
  customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name   VARCHAR(200) NOT NULL,
  phone       VARCHAR(30),
  email       VARCHAR(200),
  address     VARCHAR(300),
  CONSTRAINT uq_customers_email UNIQUE (email)
);

CREATE TABLE order_statuses (
  status_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE orders (
  order_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  INT NOT NULL,
  status_id    INT NOT NULL,
  created_at   TIMESTAMP NOT NULL,
  total_cost   NUMERIC(12,2) NOT NULL CHECK (total_cost >= 0),
  CONSTRAINT fk_orders_customer
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT fk_orders_status
    FOREIGN KEY (status_id) REFERENCES order_statuses(status_id)
);

CREATE TABLE order_items (
  order_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id    INT NOT NULL,
  order_id      INT NOT NULL,
  quantity      INT NOT NULL CHECK (quantity > 0),
  unit_price    NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),
  line_total    NUMERIC(12,2) NOT NULL CHECK (line_total >= 0),
  CONSTRAINT fk_items_product
    FOREIGN KEY (product_id) REFERENCES products(product_id),
  CONSTRAINT fk_items_order
    FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
  CONSTRAINT uq_order_product UNIQUE (order_id, product_id)
);

CREATE TABLE delivery (
  delivery_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    INT NOT NULL UNIQUE,
  address     VARCHAR(300) NOT NULL,
  time_from   TIMESTAMP NOT NULL,
  time_to     TIMESTAMP NOT NULL,
  CONSTRAINT fk_delivery_order
    FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
  CONSTRAINT chk_delivery_window CHECK (time_to >= time_from)
);

COMMIT;